### ISSUE TITLE
build error1

### ISSUE THREAD

**Issue by venkatbaytech** [android-rpi/device_brcm_rpi3#10]
*Getting the following errors *

including ./system/weaved/Android.mk ...
including ./system/webservd/Android.mk ...
including ./tools/external/fat32lib/Android.mk ...
make: **\* [out/build-aosp_arm.ninja] Killed
make: **\* Deleting file `out/build-aosp_arm.ninja'

Any reference or guidance to build sucessfully.

**Comment by freeloki** [comment]
I was getting this error because of low RAM. Is your RAM enough?

**Comment by venkatbaytech** [comment]
we have 16GB ram. so it cant be RAM issue.
