### ISSUE TITLE
Android OS for RPI4?

### ISSUE THREAD

**Issue by titanity** [android-rpi/device_brcm_rpi3#123]
Android OS for RPI4? Cant find it anywhere on the net...

**Comment by saurabhin25** [comment]
Even i am searching

**Comment by saurabhin25** [comment]
Android oR crankshaft still searching for rpi4

**Comment by ghost** [comment]
I'm working on it: https://github.com/RaspberryPiFan/device_brcm_rpi4

**Comment by saurabhin25** [comment]
Waiting for android 10 on my rpi4

**Comment by ghost** [comment]
Build it!

**Comment by ghost** [comment]
https://github.com/RaspberryPiFan/local_manifests

**Comment by saurabhin25** [comment]
How to download

**Comment by RaspberryPiFan** [comment]
RTFM!!!

**Comment by titanity** [comment]
RaspberryPiFan i cant wait to see it. Do you have a finished image ready to burn to USB for the 4gb version?

**Comment by ghost** [comment]
> RaspberryPiFan i cant wait to see it. Do you have a finished image ready to burn to USB for the 4gb version?

No, I'm sorry, I haven't build or tested this, but I'm going to do it soon. Do you need an tutorial how to build it yourself?

**Comment by ghost** [comment]
You can't build this on Windows or on Raspberry Pi, you need an PC with linux

**Comment by ghost** [comment]
Run this on Debian or Ubuntu:
```
mkdir ~/bin
PATH=~/bin:$PATH
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
cd
mkdir android
cd android
repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r2
git clone https://github.com/RaspberryPiFan/local_manifests .repo/local_manifests -b android-10
repo sync
sudo apt install gcc-arm-linux-gnueabihf libssl-dev
cd kernel/rpi
ARCH=arm scripts/kconfig/merge_config.sh arch/arm/configs/bcm2711_defconfig kernel/configs/android-base.config kernel/configs/android-recommended.config
ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make zImage
ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make dtbs
cd ../..
sudo apt install python-mako
lunch rpi3-eng
make ramdisk systemimage vendorimage
```

**Comment by ghost** [comment]
Next step:

> # Prepare sd card
>  Partitions of the card should be set-up like followings.
>   p1 256MB for BOOT : Do fdisk : W95 FAT32(LBA) & Bootable, mkfs.vfat
>   p2 640MB for /system : Do fdisk, new primary partition
>   p3 128MB for /vendor : Do fdisk, new primary partition
>   p4 remainings for /data : Do fdisk, mkfs.ext4
>  Set volume label for /data partition as userdata
>   : use -L option of mkfs.ext4, e2label command, or -n option of mkfs.vfat

**Comment by ghost** [comment]
```
cd out/target/product/rpi4
sudo dd if=system.img of=/dev/<p2> bs=1M
sudo dd if=vendor.img of=/dev/<p3> bs=1M
```
replace `<p2>` and `<p3>` with the partition

Copy
  device/brcm/rpi4/boot/* to `p1:/`
  kernel/rpi/arch/arm/boot/zImage to `p1:/`
  kernel/rpi/arch/arm/boot/dts/bcm2711-rpi-4-b.dtb to `p1:/`
  kernel/rpi/arch/arm/boot/dts/overlays/vc4-kms-v3d.dtbo to `p1:/`overlays/vc4-kms-v3d.dtbo
  out/target/product/rpi4/ramdisk.img to `p1:/`

**Comment by saurabhin25** [comment]
Sorry i am a newbee cant do this...please make a downloadable file if u can ... Its been a month searching for android for my rpi4

**Comment by ghost** [comment]
> Sorry i am a newbee cant do this...please make a downloadable file if u can ... Its been a month searching for android for my rpi4

Sorry, I can't do this at the moment, but eventually next week.

**Comment by saurabhin25** [comment]
Okay ur name will be written with golden words

**Comment by ghost** [comment]
@saurabhin25  Do you have an PC with Windows 10?

**Comment by ghost** [comment]
If yes, I can tell you how to build it.
But you can't use your PC while building.
And I don't know if it works.

**Comment by RaspberryPiFan** [comment]
But you can't use your PC while building.
And I don't know if it works.

**Comment by titanity** [comment]
Yes i do and i also got ubuntu and win10 together as multiboot

**Comment by saurabhin25** [comment]
Yes i have windws 10

**Comment by titanity** [comment]
when i run :
git clone https://github.com/android-rpi/local_manifests .repo/local_manifests -b android-10
in Ubuntu it says :
Remote branch android-10 not found in upstream origin

**Comment by titanity** [comment]
[https://ibb.co/nz3bN8M](url)

**Comment by titanity** [comment]
https://ibb.co/nz3bN8M

**Comment by Berisan** [comment]
The branch name doesn't exist, try:
git clone https://github.com/android-rpi/local_manifests .repo/local_manifests -b android10

**Comment by ghost** [comment]
You're doing it wrong.

**Comment by saurabhin25** [comment]
I have windows 10 pc please help me

**Comment by ghost** [comment]
Yes, do you have the latest win10 version?

**Comment by saurabhin25** [comment]
Yes

**Comment by ghost** [comment]
Open PowerShell as administrator

**Comment by ghost** [comment]
Type `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`

**Comment by ghost** [comment]
Reboot your PC and install this: https://www.microsoft.com/store/apps/9MSVKQC78PK6

**Comment by ghost** [comment]
Tell me when you're finished.

**Comment by ghost** [comment]
@saurabhin25  Did it work?

**Comment by ghost** [comment]
@saurabhin25 ?

**Comment by Berisan** [comment]
@RaspberryPiFan the branch name was changed. https://github.com/android-rpi/local_manifests/commit/67d814a03af6bd86d96ec5aa509d6a52d3fcc5af

**Comment by ghost** [comment]
It was a typo, I wanted to use my repository. https://github.com/RaspberryPiFan/local_manifests

**Comment by saurabhin25** [comment]
Please make a downloadable file please

**Comment by titanity** [comment]
RaspberryPiFan do you know how many people waiting for android for RPI4 atm? You are really gonna be famous if you can make a working android for RPI4... Specially if its android 10. Im on discord with ppl who is quite famous on youtube who didnt even finish a image yet

**Comment by saurabhin25** [comment]
Ur name will be written with golden words

**Comment by ghost** [comment]
I don't know if it works, but if someone wants to build it yourself, I can tell him how.

**Comment by titanity** [comment]
You use teamspeak? i got my own private server if so... im building atm...

i had a stop when repo sync .. it said:

Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by titanity** [comment]
this message i got after 10 mins runtime

**Comment by ghost** [comment]
You can contact me at discord https://discord.gg/kf4ZPqP

**Comment by saurabhin25** [comment]
Can i build this on buster

**Comment by titanity** [comment]
No you need a pc with linux

**Comment by titanity** [comment]
@RaspberryPiFan Let me know if you get the time today. Because im done with the first part. But im stuck at compiling the kernel

**Comment by ghost** [comment]
```
git clone https://github.com/raspberrypi/tools ~/tools
echo PATH=$PATH:~/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin >> ~/.bashrc
source ~/.bashrc
sudo apt-get install git bison flex libssl-dev
```

**Comment by ghost** [comment]
This will take some time...

**Comment by ghost** [comment]
Further comments: https://github.com/RaspberryPiFan/device_brcm_rpi4/issues/1

**Comment by botswanabub** [comment]
received _this_

`  HOSTCC  scripts/basic/fixdep
scripts/basic/fixdep.c:97:10: fatal error: sys/types.h: Datei oder Verzeichnis nicht gefunden
 #include <sys/types.h>
          ^~~~~~~~~~~~~
compilation terminated.
scripts/Makefile.host:90: recipe for target 'scripts/basic/fixdep' failed
make[1]: *** [scripts/basic/fixdep] Error 1
Makefile:467: recipe for target 'scripts_basic' failed
make: *** [scripts_basic] Error 2
`

_while_ 

`ARCH=arm scripts/kconfig/merge_config.sh arch/arm/configs/bcm2711_defconfig kernel/configs/android-base.config kernel/configs/android-recommended.config`

**Comment by saurabhin25** [comment]
@titanity done?

**Comment by ghost** [comment]
@botswanabub Du kannst mit mir Deutsch sprechen.

**Comment by ghost** [comment]
Ich arbeite am Problem.

**Comment by ghost** [comment]
@titanity  The conection doesn't works

**Comment by botswanabub** [comment]
@RaspberryPiFan auch gut, aber vielleicht haben ja andere auch das Problem.
Leider bin ich auf dem Feld absolut unerfahren, daher kann ich da nicht wirklich mit helfen.

**Comment by saurabhin25** [comment]
Waiting for the release

**Comment by ghost** [comment]
@botswanabub Ich konnte dein Problem nicht reproduzieren. Ich arbeite gemeinsam mit @titanity am Build, dabei ist der Fehler nicht aufgetreten. Warte am besten auf die fertige Version, wahrscheinlich erscheint sie schon morgen.

**Comment by botswanabub** [comment]
wenn ich dir mit ner Info helfen kann, sage bescheid. Ansonst vielleicht noch:

nach dem SYNC scheitert es bei mir grundsätzlich schon daran, dass er das Verzeichnis gar nicht geladen hat: `cd kernel/rpi`

**Comment by ghost** [comment]
[envsetup.txt](https://github.com/android-rpi/device_brcm_rpi3/files/3746721/envsetup.txt)

**Comment by ghost** [comment]
[gralloc_drm.txt](https://github.com/android-rpi/device_brcm_rpi3/files/3746973/gralloc_drm.txt)

**Comment by ghost** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/archive/master/mesa-master.zip?path=src%2Fgallium%2Finclude%2Fpipe

**Comment by ghost** [comment]
https://github.com/android-rpi/external_mesa3d/commit/095ca32750b64bf607ae900273032886612f4a09.diff

**Comment by ghost** [comment]
> nach dem SYNC scheitert es bei mir grundsätzlich schon daran, dass er das Verzeichnis gar nicht geladen hat: `cd kernel/rpi`

Das Problem gab es manchmal bei mir auch.
Ich update nochmal meine Repos und sag es dir dann.

**Comment by ghost** [comment]
New lunch-install
[envsetup.txt](https://github.com/android-rpi/device_brcm_rpi3/files/3747664/envsetup.txt)

**Comment by RaspberryPiFan** [comment]
### If you need help:
![discord_join_blurple](https://user-images.githubusercontent.com/49343974/67157455-b60e1e80-f32c-11e9-9611-7627987a3696.png)
https://discord.gg/AQcrHbD

**Comment by RaspberryPiFan** [comment]
[envsetup.txt](https://github.com/android-rpi/device_brcm_rpi3/files/3747720/envsetup.txt)

**Comment by ghost** [comment]
[envsetup.txt](https://github.com/android-rpi/device_brcm_rpi3/files/3747729/envsetup.txt)

**Comment by ghost** [comment]
[mesa.zip](https://github.com/android-rpi/device_brcm_rpi3/files/3748294/mesa.zip)

**Comment by ghost** [comment]
### If you need help:
![discord_join_blurple](https://user-images.githubusercontent.com/49343974/67157455-b60e1e80-f32c-11e9-9611-7627987a3696.png)
https://discord.gg/kf4ZPqP

**Comment by ghost** [comment]
[mesa.zip](https://github.com/android-rpi/device_brcm_rpi3/files/3751748/mesa.zip)

**Comment by ghost** [comment]
**https://github.com/bminor/mesa-mesa/blob/master/src/broadcom/cle/v3d_packet_v33.xml
**

**Comment by ghost** [comment]
https://raw.githubusercontent.com/bminor/mesa-mesa/master/src/broadcom/compiler/nir_to_vir.c

**Comment by ghost** [comment]
[mesa.zip](https://github.com/android-rpi/device_brcm_rpi3/files/3757152/mesa.zip)

**Comment by ghost** [comment]
https://github.com/android-rpi/device_brcm_rpi3/files/3757152/mesa.zip

**Comment by saurabhin25** [comment]
What happened friend?

**Comment by saurabhin25** [comment]
Blocked everyone or just me,?

**Comment by ghost** [comment]
You because you were really annoying and not contributing anything.

**Comment by saurabhin25** [comment]
I am very much curious abt the project 
If that is annoying you very sorry for that

**Comment by saurabhin25** [comment]
Add me please

**Comment by ghost** [comment]
No, but I'll tell you when it's finished.

**Comment by saurabhin25** [comment]
Okay

**Comment by saurabhin25** [comment]
Any updates? What abt that boot error and mesa?

**Comment by ghost** [comment]
```
sudo apt install gcc-arm-linux-gnueabihf libssl-dev python-mako git bison flex curl
mkdir ~/bin
PATH=~/bin:$PATH
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
mkdir ~/android
cd ~/android
repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r2
git clone https://github.com/RaspberryPiFan/local_manifests .repo/local_manifests -b android-10
repo sync
source device/brcm/rpi3/envsetup.sh
cd kernel/rpi
git clone https://github.com/raspberrypi/tools ~/tools
echo PATH=$PATH:~/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin >> ~/.bashrc
source ~/.bashrc
ARCH=arm scripts/kconfig/merge_config.sh arch/arm/configs/bcm2711_defconfig kernel/configs/android-base.config kernel/configs/android-base-arm.config kernel/configs/android-recommended.config
ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make zImage dtbs 
cd ../..
lunch rpi3-eng
make ramdisk systemimage vendorimage -j4
```

**Comment by saurabhin25** [comment]
Downloadable image? Or i have to run these cmds in buster?

**Comment by saurabhin25** [comment]
Please let me know the abt the progress

**Comment by ghost** [comment]
> Downloadable image? Or i have to run these cmds in buster?

Run the cmds in buster

Progress: Trying to switch from mesa3d to swiftshader

**Comment by ghost** [comment]
3%

**Comment by ghost** [comment]
36% now.

**Comment by ghost** [comment]
@saurabhin25 I unbanned saurabhgupta25 now, but you'll be read-only.
https://discord.gg/DQr3aU

**Comment by ghost** [comment]
https://raw.githubusercontent.com/android-rpi/device_brcm_rpi3/50782b36870178074d7c800deddb91e32d466c5f/AndroidProducts.mk

**Comment by rp4k** [comment]
Hi is there any update for this thread about the burnable image for rasberry pi 4b  4gb version

**Comment by karnatinagesh** [comment]
This sources i am able to build. but when i flashed into SD-card and try to boot the device 3B+ i get a black screen and i see the RED LED light always on. i don't see the Green one on not even once.
SO ONLY RPI4 is supported. if you how to modify the changes for 3b+ please let know the steps or any document is available.

regards,
Nageswara

**Comment by titanity** [comment]
Nageswara where can i DL the suported image file for RPI4 so i can test it? Join the discord and write me if you got the llink... im eager to see if you get it to work

**Comment by titanity** [comment]
This sources i am able to build. but when i flashed into SD-card and try to boot the device 3B+ i get a black screen and i see the RED LED light always on. i don't see the Green one on not even once.
SO ONLY RPI4 is supported. if you how to modify the changes for 3b+ please let know the steps or any document is available.

regards,
Nageswara

Nageswara where can i DL the suported image file for RPI4 so i can test it? Join the discord and write me if you got the llink... im eager to see if you get it to work

**Comment by titanity** [comment]
> This sources i am able to build. but when i flashed into SD-card and try to boot the device 3B+ i get a black screen and i see the RED LED light always on. i don't see the Green one on not even once.
> SO ONLY RPI4 is supported. if you how to modify the changes for 3b+ please let know the steps or any document is available.
> 
> regards,
> Nageswara

Nageswara where can i DL the suported image file for RPI4 so i can test it? Join the discord and write me if you got the llink... im eager to see if you get it to work

**Comment by karnatinagesh** [comment]
> > This sources i am able to build. but when i flashed into SD-card and try to boot the device 3B+ i get a black screen and i see the RED LED light always on. i don't see the Green one on not even once.
> > SO ONLY RPI4 is supported. if you how to modify the changes for 3b+ please let know the steps or any document is available.
> > regards,
> > Nageswara
> 
> Nageswara where can i DL the suported image file for RPI4 so i can test it? Join the discord and write me if you got the llink... im eager to see if you get it to work

i downloaded the sources from the steps mentioned in 
https://github.com/android-rpi/local_manifests/tree/android10 
as well as 
https://github.com/android-rpi/device_brcm_rpi3/tree/android10
then i built the sources to get all the necesssary bianries.
i flashed the build into the SD card.
Latest updates: i am able to boot the raspberry pi 3b+ with the build from above sources.
but the display is not up.
from the shell i can see the Kernel and Android are up and running but not display.

regards,
Nageswara

**Comment by titanity** [comment]
I havent learn to compile or edit yet. Thats why i follow what you guys are talking about to see if i can learn a bit. Started 1 year ago with my first board RPI3b and didnt know anything about arm, computing, linux or anything. And didnt have anyone at all to ask or talk to about the new world with the small computers and the new OS called linux. So after 4 months of 100% fail missions in linux then i had my very first victory. compiling a u-boot for a armbian OS... which was a automated script (.sh) haha. but then again i learned how to start the script (sudo ./learnlinuxffsnow.sh) all i experienced with small board computing i have learned from forums and youtube and still doing it the day today. So i search for android OS for RPI4 4gb in a compiled and ready to burn image file. Enough of my boring non knowledge history. I have been searching for it every day since i bought the RPI4. Asked on many youtubers comment section for the iso file.... Nothing yet. So thats why i cant wait until the day where i can drop a iso file onto micro sd and start up a android OS. IF android 10 is the version then we make history which isnt  completed yet at all in the world. So my father just died and left me a computer which i installed linux on and told raspberrypifan he can use it as he likes, do what he wants to get closer to a final build. So i hope we get there in time before everyone else :)

endline: its friken a huge step for me that i get to know RPIfan in this thread. He is the very first i ever could ask question to and got the help i needed. So cant thank him enough. and i hope this new community here dont walk away even after the goal is reached!

**Comment by ghost** [comment]
@karnatinagesh I think you should not post that in this issue. This repo is for Raspberry Pi 3B and 3B+. Do you want a compiled build for 3B+?

**Comment by ghost** [comment]
And what sources did you build?

**Comment by karnatinagesh** [comment]
Yes I am building for raspberry pi 3b+.

**Comment by ghost** [comment]
@karnatinagesh Use device_brcm_rpi3, it's working on pi 3b+

**Comment by vonneucode** [comment]
Hello @RaspberryPiFan, i have got the swiftshader display up on a raspberry pi 4, very early stage, android10 with the basic ui for android TV, it is barely usable, but I'll see how far I can get with it

**Comment by ghost** [comment]
@vonneucode great work! is the build/code available online?

**Comment by peyo-hd** [comment]
Go to https://github.com/android-rpi/device_arpi_rpi4
