### ISSUE TITLE
No wallpaper

### ISSUE THREAD

**Issue by ikalkov** [android-rpi/device_brcm_rpi3#14]
Hi,

do you actually have a wallpaper working? On my device it stays black even after choosing it with the wallpaper manager (long click on the desktop). Nothing happens there and I see no errors in the Logcat. Any ideas?

Best regards,
Igor

**Comment by robherring** [comment]
It's some common problem in mesa or drm_hwcomposer.

**Comment by ikalkov** [comment]
@robherring Thanks for the info. Is there any hints to what exactly (method name, line nr., etc.) is not working? I would take a look into it, if nobody yet did.

**Comment by robherring** [comment]
@ikalkov I don't have much idea. There's an error from hwc "failed to squash layer" that may be related.
