### ISSUE TITLE
build error wpa.te

### ISSUE THREAD

**Issue by vmaskday** [android-rpi/device_brcm_rpi3#21]
# line 1 "device/brcm/rpi3/sepolicy/wpa.te"

```
    allow wpa self:netlink_generic_socket { create { ioctl read getattr
    write setattr lock append bind connect getopt setopt shutdown } };role
    r;
```

---

just do : #allow wpa self:netlink_generic_socket create_socket_perms;

**Comment by peyo-hd** [comment]
Build issue might be covered by the forum.
https://groups.google.com/forum/#!topic/android-rpi
