### ISSUE TITLE
Fix bluetooth

### ISSUE THREAD

**Issue by secuflag** [android-rpi/device_brcm_rpi3#22]
Hey @peyo-hd,

I managed to fix the bluetooth, feel free to pick what you need to include the fix in your repository.

https://github.com/Android-RPi3/android_device_brcm_rpi3/commit/5c65f90cec1ea06b51879ed5ca3373c02f8fe635

**Comment by peyo-hd** [comment]
Pulled the commit omitting a2dp.
I'd like to let a2dp be maintained by others for a while.

**Comment by peyo-hd** [comment]
Applied.
