### ISSUE TITLE
No apps found except settings and adb not working 

### ISSUE THREAD

**Issue by ramu472** [android-rpi/device_brcm_rpi3#24]
I installed android 6.0.1( n preview branch) on rpi3 successfully. But here after installation i didnt find any inbuilt app. Adb is also not working so not able to install any apk file..
Pls help me.

**Comment by freeloki** [comment]
Try to build tablet version. Not android tv. I fixed my problem doing this.

**Comment by ramu472** [comment]
pls give the source code path for android tablet version for rpi3.
Thanks for help.

**Comment by ramu472** [comment]
Previously i downloded from this link
https://github.com/peyo-hd/local_manifests/tree/npv

**Comment by peyo-hd** [comment]
https://groups.google.com/forum/#!topic/android-rpi
