### ISSUE TITLE
patch fix for mesa RGB issue and Launcher issue.

### ISSUE THREAD

**Issue by ric96** [android-rpi/device_brcm_rpi3#25]
https://sourceforge.net/p/android-x86/frameworks_native/ci/ea788ff0c6ca445fc8e7f634cd19ec9bca738830/

This path from android-x86 solves both the broken launcher and mesa RGB issue that caused angry birds game to have wrong RGB rendering.

**Comment by peyo-hd** [comment]
The patch is effective. I added following guide to README.
https://github.com/peyo-hd/device_brcm_rpi3/wiki#use-hal_pixel_format_bgra_8888

**Comment by secuflag** [comment]
Nice,

Thanks!

**Comment by peyo-hd** [comment]
Applied.
