### ISSUE TITLE
AtvRemoteService missing lib/ directory

### ISSUE THREAD

**Issue by ShadowEO** [android-rpi/device_brcm_rpi3#26]
This is more of an enhancement request:

The AndroidTV Remote Service will work, but it's missing the uinputbridge library from it's priv-app folder, I pulled it from the system image of the molly (ADT-1) and placed it in the AtvRemoteService folder and now the ATV Remote App works.

**Comment by ShadowEO** [comment]
Just realized this is in the wrong repo for the ATV overlay... woops, sorry about that..

**Comment by peyo-hd** [comment]
Then let's close it.
