### ISSUE TITLE
No video on Panasonic Viera TV

### ISSUE THREAD

**Issue by geekpersonman** [android-rpi/device_brcm_rpi3#29]
Shows RPI test Rainbow square then just goes blank. Does connect to the network though. TV only supports up to 1080i

**Comment by moonrise007** [comment]
Hello. I have Panasonic Viera TV with support up to 1080p 50/60 HZ. I see same behavior. Is there a way how to debug / check this problem ? It is working fine when I connect RPi to PC monitor. Thx

**Comment by IceDragonUA** [comment]
problem can be solved by change
debug.drm.mode.force= "pixel_width x pixel_height"
in /system/build.prop file

for this you should install adb on you PC
than

adb connect ip_of_device
adb root
adb remount
adb pull /system/build.prop

change line for example to
debug.drm.mode.force="1280x720"

than

adb push build.prop /system/build.prop
adb reboot

**Comment by caipivara** [comment]
@IceDragonUA this setting is set in `build.prop` without ""

I mean, its already like:
```
debug.drm.mode.force=1280x720
````

Not like:
````
debug.drm.mode.force="1280x720"
```

Tried both options but no success

**Comment by ikalkov** [comment]
I'll close this issue as the solution was provided above. For other questions concerning video configuration please refer to the discussion group: https://groups.google.com/forum/#!topic/android-rpi/ciILTnABiKA
