### ISSUE TITLE
interrupter.o: file is empty on incremental builds

### ISSUE THREAD

**Issue by adipascu** [android-rpi/device_brcm_rpi3#31]
I am getting `error: out/host/linux-x86/obj/SHARED_LIBRARIES/interrupter_intermediates/interrupter.o: file is empty`.

My first build ran fine, all the others fail with this error.
I do not run ccache but I respected the other mandatory instructions from this project and android.com

What I tried so far:
- Remove all my changes using `repo forall -vc "git reset --hard"`
- `make clean`
- `make clobber`
- deleting the content of the **out** directory
- deleting all directories excepting **.repo** and running `repo sync`
- `source build/envsetup.sh` and `lunch rpi3-eng`
- restarted the os (ubuntu) 

How can I fix my build ?

**Comment by peyo-hd** [comment]
Go to the forum for build troubleshoot :
https://groups.google.com/forum/#!forum/android-rpi
