### ISSUE TITLE
Boot process stuck at android animation logo

### ISSUE THREAD

**Issue by sandeepmvd** [android-rpi/device_brcm_rpi3#33]
Hi,

The boot process hangs at android logo. I waited for a long time but the home screen never comes up.
What could be possible going wrong? Need your suggestions.

I need ethernet working. Hence I am not able to use standard build at https://github.com/Android-RPi3/android_releases_rpi3/releases as it does not include ethernet support.

I have partitioned as follows

device Name type flags size:
/dev/sdf1 BOOT FAT32(LBA) boot 512M
/dev/sdf2 system ext4 512M
/dev/sdf3 cache ext4 512M
/dev/sdf4 data f2fs 28G

Please let me know if you any issues with above partition table.

Thanks in advance.

Best Regards,
Sandeep

**Comment by sandeepmvd** [comment]
Is anyone else facing this issue or is it only me? Please respond.

**Comment by peyo-hd** [comment]
For build troubleshoot, go to the forum : 
https://groups.google.com/forum/#!forum/android-rpi

**Comment by jonathanisaac** [comment]
@binary-nerd did you solve it? I have the same problem and I had no response in the group.

**Comment by sandeepmvd** [comment]
@jonathanisaac I was able to get through it. But sorry, I cannot remember what did I do to resolve it. May be I had used an official build that included ethernet support or I disable a few modules here and there. Not really sure. I am sorry.
