### ISSUE TITLE
Boot with no display

### ISSUE THREAD

**Issue by ikalkov** [android-rpi/device_brcm_rpi3#34]
The drm_gralloc project expects the HDMI connector to provide at least one mode for correct initialization. This prevents RPi3 from booting if the cable is not connected. I can image such setups to be interesting for automation or other tasks, where user application is implemented to start after boot and do some useful stuff.

Its seems to be fixable with just a couple lines of code. I'll test it tomorrow and create a pull request in the drm_gralloc project if you don't see any possible issues with it.

**Comment by peyo-hd** [comment]
Done by Igor on https://github.com/peyo-hd/external_drm_gralloc.
