### ISSUE TITLE
SDTV Mode

### ISSUE THREAD

**Issue by alikemalocalan** [android-rpi/device_brcm_rpi3#4]
Plz add to sdtv mode configurations  on  boot setting

**Comment by ric96** [comment]
TV out is not yet supported in the GPU Driver
https://github.com/anholt/linux/issues/14

**Comment by dengleiyy** [comment]
Dear All:
  In order to support sdtv_mode, how should we transplant the GPU driver?
  I need you help badly.
Thanks.

**Comment by vmaskday** [comment]
the defconfig not enable CONFIG_FB_BCM2708.

**Comment by peyo-hd** [comment]
Let this requirement done by upstream projects - like raspberrypi or anholt.
