### ISSUE TITLE
do you have try to use adb to debug rpi os ?

### ISSUE THREAD

**Issue by wellcomez** [android-rpi/device_brcm_rpi3#46]
I haven't try it and i hope it can work. Do you have any experience can share with me?

**Comment by ikalkov** [comment]
@wellcomez Why are you creating an issue if you didn't try it yet?

**Comment by wellcomez** [comment]
@peyo-hd can you give me suggestion for debug.

**Comment by ikalkov** [comment]
This issue doesn't describe a functional problem, but rather a general question. Please refer to the discussion group for more information.
