### ISSUE TITLE
google play inserted version?

### ISSUE THREAD

**Issue by halukmy** [android-rpi/device_brcm_rpi3#48]
please send google play enabled version 👍

**Comment by ikalkov** [comment]
Including Google Play Services without paying licensing fees to Google is not legal.

**Comment by nikiwaibel** [comment]
within https://git.embedded.rwth-aachen.de/rtandroid/downloads/raspberry-pi/ there is a script that adds the play service and it's app. it may be possible to develop a more general version of it …

[edit] … actually it seems quite generic already. maybe it works out of the box?

**Comment by ikalkov** [comment]
@nikiwaibel The script is designed to work with all distributions and will work especially with this one, as I used this repo originally for my work. I think he just doesn't like starting a script at all.

**Comment by nikiwaibel** [comment]
@ikalkov i see.  @halukmy it is definitely not allowed to include the play store. only certified devices have the right to include it out of the box.
