### ISSUE TITLE
let's decide on system partition size

### ISSUE THREAD

**Issue by ric96** [android-rpi/device_brcm_rpi3#54]
I feel like 512 mb is too little specially if someone wants to add gapps packages. 
1024mb or 2048mb ?

**Comment by ikalkov** [comment]
Did we decide it will stay this way? I'm not sure :)

**Comment by ric96** [comment]
if every one is fine with it i can do it in the nougat-tablet branch

**Comment by ikalkov** [comment]
I'm fine with the "tablet"-branch. I assume we can close the issue?
