### ISSUE TITLE
When RPI3 Connected to TV getting Message "Unsupported signal. Check your device output"

### ISSUE THREAD

**Issue by bhaskarchalla** [android-rpi/device_brcm_rpi3#59]
Hi,
when my raspberry pi 3 is connected to tv , I am getting Message Unsupported signal. Check your device output. 
Only for android if we have rasbeanOS or Kodi  it works fine.
And using 44 inch Sony TV

**Comment by ikalkov** [comment]
You need to set the correct configuration for your TV.
Please refer to the discussion group: https://groups.google.com/forum/#!topic/android-rpi/ciILTnABiKA
