### ISSUE TITLE
lunch rpi3-eng command fails

### ISSUE THREAD

**Issue by venkatbaytech** [android-rpi/device_brcm_rpi3#6]
able to run rpi2-eng.. but rpi3-eng fails as below
baytech@lab-HP:~/piandroid$ lunch rpi3-eng
build/core/product_config.mk:222: **\* Can not locate config makefile for product "rpi3".  Stop.

*\* Don't have a product spec for: 'rpi3'
*\* Do you have the right repo manifest?
where do I miss?

**Comment by ric96** [comment]
make sure the branch for local manifest is -npv
other wise you get for rpi2 and not rpi3
https://github.com/peyo-hd/local_manifests/tree/npv

**Comment by venkatbaytech** [comment]
U r correct i am able to run for rpi3.
