### ISSUE TITLE
Is it necessary to patch GLSurfaceView?

### ISSUE THREAD

**Issue by yangxq** [android-rpi/device_brcm_rpi3#7]
As mentioned in device_brcm_rpi2, the mesa3d vc4 build only support RGB 888, Alpha 8, Depth 24.
Is it the same on rpi3?

**Comment by peyo-hd** [comment]
Yes. same to rpi2

**Comment by robherring** [comment]
This is almost fixed in mesa mainline. You need commit "st/dri: add 32-bit RGBX/RGBA formats" and a couple before it. It got reverted though because it broke X11.
