### ISSUE TITLE
CPUSET in rpi3 with Android 7

### ISSUE THREAD

**Issue by AlejandroPerezRuiz** [android-rpi/device_brcm_rpi3#75]
I am trying to use CPUSET to create some groups of cpus with tasks but I don't know how to do it. There is a folder in the system /dev/cpuset that it seems to contain the structure to work with them but it doesn't have all the staffs. 
When I try to mount the cpuset in a directory, it doesn't work:
mount -t cpuset cpuset /dev/cpuset --> mount: 'cpuset'->'/dev/cpuset/': No such file or directory
Do you have any idea if the cpusets are OK in the rpi3?

**Comment by ikalkov** [comment]
@AlejandroPerezRuiz, may I ask how you solved it?
