### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by venkatbaytech** [android-rpi/device_brcm_rpi3#8]
in rpi3 build, getting the below error

build/core/base_rules.mk:181: **\* system/tools/aidl: MODULE.linux.EXECUTABLES.aidl already defined by frameworks/base/tools/aidl.

Any help on this.

**Comment by ikalkov** [comment]
Interestingly, I get another error while building rpi3:

external/mesa3d/src/glsl/nir/nir.h: At top level:
external/mesa3d/src/glsl/nir/nir.h:41:25: fatal error: nir_opcodes.h: No such file or directory
 #include "nir_opcodes.h"

This file has to be autogenerated by the building process, but it obviously isn't happening. Any ideas? May be something missing in the toolchain? The same repo was working on rpi2 (o_O)!
