### ISSUE TITLE
Settings keeps stopping

### ISSUE THREAD

**Issue by yangjiel** [android-rpi/device_brcm_rpi3#90]
Hello there,

First of all, thank you for making Nougat Android support for RPI3.
I followed your instruction to compile and load the image into sd card. After the Android booted, the home screen is buggy, shows multiple mouses, lines and shapes but the apps page, browser are good.

However, the main problem is I cannot use the setting, after I clicked any one of the options in the settings, it just crash and saying: Settings keeps stopping. I want to install a terminal to see the boot log etc, it requires to add the account in the setting.

Is there anything wrong with my configuration?

**Comment by ric96** [comment]
https://github.com/android-rpi/device_brcm_rpi3/wiki/Runtime-Errors

**Comment by yangjiel** [comment]
Oh well, it seems I skipped a step applying patches. Thank you.
