### ISSUE TITLE
Cannot add account

### ISSUE THREAD

**Issue by yangjiel** [android-rpi/device_brcm_rpi3#91]
I clicked the Add account multiple times but had no response. Thus, I am not be able to install software from google play. I tried to download apk file from the default browser but it didn't work. As I am new to android, what should I do to install some apps like the termux? Is there anyway to allow me to install apps?

**Comment by ValkiryXDA** [comment]
You should be able to ADB over wifi and push files to /data/ or /system/app 

There is a program you can use https://forum.xda-developers.com/showthread.php?t=2707556

**Comment by yangjiel** [comment]
This should work. Thank you.
